version: '3'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiz-pet-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: "pet-postgres"
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:

