// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbs

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Question struct {
	ID           int32
	TestID       int32
	QuestionText sql.NullString
	Options      pqtype.NullRawMessage
}

type Test struct {
	ID            int32
	Title         string
	Description   string
	PublishedDate time.Time
}

type Usersresult struct {
	Sessionid uuid.UUID
	Results   pqtype.NullRawMessage
}
